/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.apache.jena.riot.avro;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Kind implements org.apache.avro.generic.GenericEnumSymbol<Kind> {
  IRI, PN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Kind\",\"namespace\":\"org.apache.jena.riot.avro\",\"symbols\":[\"IRI\",\"PN\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
